a = c(5,5.6,1,4,-5)
a[1]
b=a[2:4]
d=a[c(1,3,5)]
2*a
b%%3
e=3/d
print(e)
print(log(d*e))
g=c(sqrt(2),log(10))
cat("this is g: ", g, "\n", sep="")
print(d)
print(e)
print(e[d==5])
print(a)
print(a[-3])
print(is.vector(d))
print(a)
a = c(a,1)
print(a)
mymat = matrix(a,nrow=2)
print(mymat)
mymat2 = matrix(a,nrow=2, byrow=T)
print(mymat)

print(mymat+mymat2)
print(mymat*mymat2)
print(t(mymat)%*%mymat2)
print(crossprod(mymat,mymat2))
mymat3 = matrix(a)
print(mymat3)
mymat3 = t(matrix(a))
print(mymat3)
mymat3 = matrix(t(a))
print(mymat3)
x1=matrix(1:20,nrow=5)
print(x1)
x2=matrix(1:20,nrow=5,byrow=T)
print(x2)
a=x1%*%t(x2)
print(a)
c=x1*x2
print(c)
print(dim(x1))
print(c)
print(c[,2])
print(c[c(3,4),])
print(rbind(x1,x2))
print(cbind(x1,x2))
print(x1)
print(apply(x1,1,sum))
print(apply(x1,2,sum))
print(apply(x1,c(1,2),sum))
print(apply(x1, 2, mean))
print(apply(x1, 2, mean, trim=.2))
x <- cbind(x1 = 3, x2 = c(4:1, 2:5))
print(x1)
print(x2)
print(x)
print(apply(x, 2, mean, trim = .2))
